---
- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install dependencies
  apt:
    name:
      - curl
      - wget
      - vim
      - net-tools
      - gnupg
      - unzip
    state: present

- name: Download AWS CLI v2 installer
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"

- name: Unzip AWS CLI installer
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes

- name: Install AWS CLI
  command:
    cmd: "/tmp/aws/install"

- name: Verify AWS CLI installation
  command: aws --version
  register: aws_version_output
  changed_when: false

- name: Display AWS CLI version
  debug:
    msg: "{{ aws_version_output.stdout }}"
