apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-onebot-eks-cluster-v2
  region: us-east-1
  version: "1.31"
  tags: 
    karpenter.sh/discovery: dev-onebot-eks-cluster-v2

vpc:
  id: vpc-0c29cbcedcce79bb1
  subnets:
    private:
      us-east-1a: { id: subnet-0272b68cca109c1f2 }  
      us-east-1b: { id: subnet-0378671215219ca68 }
      us-east-1c: { id: subnet-0cd7b8f06b59893ce }

  publicAccessCIDRs:
    - "49.206.7.3/32"
  clusterEndpoints:
    privateAccess: true  
    publicAccess: true

managedNodeGroups:
  - name: dev-setnext-ng-private
    instanceType: m5.xlarge
    # launch nodegroup in private subnets
    privateNetworking: true
    minSize: 1
    desiredCapacity: 1
    maxSize: 10
    volumeSize: 30
    labels: {zone: secured}
    tags:
      nodegroup-role: worker
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  - name: dev-setnext-ng-monitoring
    instanceType: m5.xlarge
    labels:
      monitoring: "true"
      zone: secured 
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

    taints:
      - key: "monitoring"
        value: "only"
        effect: "NoSchedule"
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    privateNetworking: true
    ssh: 
      enableSsm: true
    
addons:
  - name: aws-ebs-csi-driver
    version: latest
  - name: eks-pod-identity-agent
    version: latest

addonsConfig:    
   autoApplyPodIdentityAssociations: true

iam:
  withOIDC: true

